import { Property } from "./types";

// Hardcoded from CIRCA-PROPERTY LISTING Google Sheet
// Spreadsheet ID: 17nryG-WPTeSxC1n2XiPuRZ1h2CByXUQPlttul35P6Ck
export const PROPERTIES: Property[] = [
  {
    name: "Casa Valley",
    location: "Playa Venao",
    category: "Project",
    lotSize: "600",
    constructionSize: "280",
    pricePerSqm: "",
    price: "550,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Commercial area, Green areas, Padel courts",
    ownerDeveloper: "Papaya Holdings (Tomer)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 3 months",
  },
  {
    name: "Villa Brisa",
    location: "Venao Village",
    category: "House",
    lotSize: "646",
    constructionSize: "272",
    pricePerSqm: "",
    price: "900,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "2",
    amenities: "Pool, BBQ, Solar, Guests house",
    ownerDeveloper: "Green Ace (Aviad)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 6 months",
  },
  {
    name: "Duplex Villa",
    location: "Lomas Venao",
    category: "Duplex",
    lotSize: "488",
    constructionSize: "180",
    pricePerSqm: "",
    price: "500,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Pool, Outdoor areas",
    ownerDeveloper: "VEO Construction (Oded)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 3 months",
  },
  {
    name: "Villa Marina 402",
    location: "Villa Marina",
    category: "House",
    lotSize: "",
    constructionSize: "180",
    pricePerSqm: "",
    price: "650,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Pool, Future plans, BBQ area",
    ownerDeveloper: "Azul",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Completely furnished",
  },
  {
    name: "Casa Ceviche",
    location: "Blue Venao",
    category: "House",
    lotSize: "300",
    constructionSize: "160",
    pricePerSqm: "",
    price: "725,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Pirawa Properties",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Completely furnished",
  },
  {
    name: "Blue B21",
    location: "Blue Venao",
    category: "Apartment",
    lotSize: "",
    constructionSize: "107",
    pricePerSqm: "",
    price: "350,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, Terrace area",
    ownerDeveloper: "Michael / Azuero Rental",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Furnished",
  },
  {
    name: "Villa Umutu",
    location: "Canas",
    category: "House",
    lotSize: "3342",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Pool, Terrace, Solar, Ocean view",
    ownerDeveloper: "Margarita",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Furnished",
  },
  {
    name: "Surf Lodge Residence",
    location: "Playa Venao",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Surf lodge, Beach access",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Pre-sale investors",
  },
  {
    name: "Blue Venao Duplex 47B",
    location: "Blue Venao",
    category: "Duplex",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Beach Club",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
  },
  {
    name: "Hermitage El Ciruelo",
    location: "El Ciruelo",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Mountain views, Nature",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
  },
  {
    name: "Shahak Mountain",
    location: "Mountain area",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Mountain views",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
  },
  {
    name: "Solaris Moledet",
    location: "Moledet",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Solar powered",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
  },
  {
    name: "Villa Oro",
    location: "Playa Venao",
    category: "House",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Pool, Ocean view",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
  },
];

export function searchProperties(query: string): Property[] {
  const q = query.toLowerCase();
  return PROPERTIES.filter((p) => {
    const searchable = [
      p.name,
      p.location,
      p.category,
      p.amenities,
      p.price,
      p.notes,
      p.bedrooms ? `${p.bedrooms} bedroom` : "",
      p.bathrooms ? `${p.bathrooms} bathroom` : "",
    ]
      .join(" ")
      .toLowerCase();
    return q.split(" ").some((word) => word.length > 2 && searchable.includes(word));
  });
}
