import { Property } from "./types";

// Synced from CIRCA-PROPERTY LISTING Google Sheet (2026-03-23)
// Spreadsheet ID: 17nryG-WPTeSxC1n2XiPuRZ1h2CByXUQPlttul35P6Ck
export const PROPERTIES: Property[] = [
  {
    name: "Casa Valley",
    location: "Playa Venao",
    category: "Project",
    lotSize: "600",
    constructionSize: "280",
    pricePerSqm: "$1,964.29",
    price: "550,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Commercial area, Green areas, Padel courts",
    ownerDeveloper: "Papaya Holdings (Tomer)",
    ownerContact: "972 54 56 21 449",
    driveFolderLink: "https://drive.google.com/file/d/1wn5ep8fcZ1D7Y1peulwxMxaUbFqqbZ2I/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Ready in 3 months",
    imageUrl: "https://lh3.googleusercontent.com/d/1wn5ep8fcZ1D7Y1peulwxMxaUbFqqbZ2I=w800",
  },
  {
    name: "Villa Brisa",
    location: "Venao Village",
    category: "House",
    lotSize: "646",
    constructionSize: "272",
    pricePerSqm: "$3,308.82",
    price: "900,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "2",
    amenities: "Pool, BBQ, Solar system, Guest house",
    ownerDeveloper: "Green Ace Aviad",
    ownerContact: "507 6885 5232",
    driveFolderLink: "https://drive.google.com/file/d/1kED4MthqGxGbVnx2sdb5I9IjhQFCe-dR/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Ready in 6 months",
    imageUrl: "https://lh3.googleusercontent.com/d/1kED4MthqGxGbVnx2sdb5I9IjhQFCe-dR=w800",
  },
  {
    name: "Duplex Villa",
    location: "Lomas Venao",
    category: "Duplex",
    lotSize: "488",
    constructionSize: "180",
    pricePerSqm: "$2,777.78",
    price: "500,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Pool, Outdoor areas",
    ownerDeveloper: "VEO Construction Oded",
    ownerContact: "507 6237 3577",
    driveFolderLink: "",
    status: "Available",
    legalDocs: true,
    notes: "Ready in 3 months",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=500&fit=crop",
  },
  {
    name: "Villa Marina 402",
    location: "Villa Marina",
    category: "House",
    lotSize: "",
    constructionSize: "180",
    pricePerSqm: "$3,611.11",
    price: "650,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Pool, Future plans, BBQ area",
    ownerDeveloper: "Azul",
    ownerContact: "507 6460 7739",
    driveFolderLink: "",
    status: "Available",
    legalDocs: true,
    notes: "Completely furnished",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=500&fit=crop",
  },
  {
    name: "Casa Ceviche",
    location: "Blue Venao",
    category: "House",
    lotSize: "300",
    constructionSize: "160",
    pricePerSqm: "$4,531.25",
    price: "725,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Pirawa Properties",
    ownerContact: "6898 9669",
    driveFolderLink: "https://drive.google.com/file/d/1nlHryQKtIaLVhSJKF_W9uvlSI7hsU6By/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Completely furnished",
    imageUrl: "https://lh3.googleusercontent.com/d/1nlHryQKtIaLVhSJKF_W9uvlSI7hsU6By=w800",
  },
  {
    name: "Blue B21",
    location: "Blue Venao",
    category: "Apartment",
    lotSize: "",
    constructionSize: "107",
    pricePerSqm: "$3,271.03",
    price: "350,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, Terrace area",
    ownerDeveloper: "Michael/Azuero Rental",
    ownerContact: "507 6225 6363",
    driveFolderLink: "https://drive.google.com/file/d/1yqzAUx246brhDphLMtgSTP7-r6YwxP5r/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Furnished",
    imageUrl: "https://lh3.googleusercontent.com/d/1yqzAUx246brhDphLMtgSTP7-r6YwxP5r=w800",
  },
  {
    name: "Villa Umutu",
    location: "Canas",
    category: "House",
    lotSize: "3342",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "3",
    bathrooms: "2.5",
    parking: "2",
    amenities: "Pool, Terrace, Solar system, Ocean view",
    ownerDeveloper: "Margarita",
    ownerContact: "507 67785469",
    driveFolderLink: "https://drive.google.com/file/d/1CMraaJGlbbs-J_9BbPWmnRSBG0cC8FBW/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Furnished",
    imageUrl: "https://lh3.googleusercontent.com/d/1CMraaJGlbbs-J_9BbPWmnRSBG0cC8FBW=w800",
  },
  {
    name: "Surf Lodge Residence",
    location: "Playa Venao",
    category: "Project",
    lotSize: "100,000",
    constructionSize: "",
    pricePerSqm: "3,000",
    price: "208,000 - 841,500",
    bedrooms: "Studio - 4",
    bathrooms: "1 - 4",
    parking: "",
    amenities: "50m Pool, Beach Club, Gym, Outdoor Gym, Bakery & Cafe, Co-working Space, Surf Lodge, Yoga Deck, On-site Shopping, Social Area, Commercial Area, Storage Units",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Pre-sale",
    legalDocs: false,
    notes: "Early Bird pricing at $3,000/m2 (25% discount vs $4,000/m2 final price). 63 units across 7 buildings. Eco-friendly development with rainwater harvesting and sustainable materials.",
    imageUrl: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=500&fit=crop",
    totalUnits: 63,
    landSize: "10 hectares",
    unitTypes: [
      { name: "Type A - Ground Floor", bedrooms: 3, bathrooms: 2, indoorSqm: 123, outdoorSqm: 25, priceFrom: 369000, priceTo: 444000 },
      { name: "Type A/C - First Floor", bedrooms: 2, bathrooms: 2, indoorSqm: 93, outdoorSqm: 13, priceFrom: 279000, priceTo: 318000 },
      { name: "Type B - First Floor", bedrooms: 2, bathrooms: 2, indoorSqm: 87, outdoorSqm: 26, priceFrom: 261000, priceTo: 339000 },
      { name: "Type D - Studio", bedrooms: 0, bathrooms: 1, indoorSqm: 63, outdoorSqm: 13, priceFrom: 189000, priceTo: 228000 },
      { name: "Type E - Second Floor", bedrooms: 2, bathrooms: 2, indoorSqm: 69, outdoorSqm: 26, priceFrom: 207000, priceTo: 285000 },
      { name: "Penthouse", bedrooms: 4, bathrooms: 4, indoorSqm: 223, outdoorSqm: 115, priceFrom: 669000, priceTo: 841500 },
    ],
    rentalProjections: [
      { unitType: "Studio", occupancyRate: "65%", nightlyRate: 100, monthlyRent: 1950 },
      { unitType: "2 Bedrooms", occupancyRate: "65%", nightlyRate: 150, monthlyRent: 2925 },
      { unitType: "3 Bedrooms", occupancyRate: "65%", nightlyRate: 200, monthlyRent: 3900 },
    ],
    roiEstimate: "7-9%",
    marketPricePerSqm: "$4,400 - $4,800 (beachside), $3,300 - $3,600 (second row)",
    entryPricePerSqm: "$3,000 (Early Bird - 25% below market)",
    ecoFeatures: [
      "Tree replanting for every tree removed",
      "Careful tree mapping to minimize impact",
      "Sustainable locally sourced materials",
      "Rainwater harvesting and water recycling",
      "Energy-efficient design blending with nature",
    ],
    communityFeatures: [
      "International school nearby",
      "30+ restaurants, hotels, shops, surf schools",
      "Upcoming commercial plaza with banks, clinic, gym",
      "New hospital in Chitre",
      "Venao Creative Village for entrepreneurs",
      "Direct flights from Pedasi to Panama City",
      "Soccer field, footvolley, paddle court",
    ],
    description: "Premium condo development on 10 hectares in Playa Venao. 63 luxury units across 7 buildings with full-service property management. USD economy, no capital gains tax, property tax exemptions up to 20 years.",
  },
  {
    name: "Duplex 47 B",
    location: "Blue Venao",
    category: "Duplex",
    lotSize: "",
    constructionSize: "282",
    pricePerSqm: "$2,659.57",
    price: "750,000",
    bedrooms: "3",
    bathrooms: "3.5",
    parking: "1",
    amenities: "Beach Club, Penthouse, Rooftop",
    ownerDeveloper: "Michael",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/file/d/1s9BKLTABO0WMFCikN0PyOz-cR6SI9yTz/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Ready in 6 months, option to add private jacuzzi",
    imageUrl: "https://lh3.googleusercontent.com/d/1s9BKLTABO0WMFCikN0PyOz-cR6SI9yTz=w800",
  },
  {
    name: "Duplex 46 A",
    location: "Blue Venao",
    category: "Duplex",
    lotSize: "",
    constructionSize: "205",
    pricePerSqm: "$3,560.98",
    price: "730,000",
    bedrooms: "3",
    bathrooms: "3.5",
    parking: "1",
    amenities: "Beach Club, Penthouse, Rooftop",
    ownerDeveloper: "Michael",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/file/d/1s9BKLTABO0WMFCikN0PyOz-cR6SI9yTz/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Ready in 6 months, ground floor area, option to add pool",
    imageUrl: "https://lh3.googleusercontent.com/d/1s9BKLTABO0WMFCikN0PyOz-cR6SI9yTz=w800",
  },
  {
    name: "Villa Marina Condo Torre 100",
    location: "Villa Marina",
    category: "Condo",
    lotSize: "",
    constructionSize: "132",
    pricePerSqm: "$3,030.30",
    price: "400,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Signature Beach Club, Sports activities and Spa, Bicycle trails, 40-room hotel with property management",
    ownerDeveloper: "Michael",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/file/d/1xn9CDHxN8wsMwQULWMfgZHGiyjSRKgZB/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "2028",
    imageUrl: "https://lh3.googleusercontent.com/d/1xn9CDHxN8wsMwQULWMfgZHGiyjSRKgZB=w800",
  },
  {
    name: "Villa Marina Condo Torre 200",
    location: "Villa Marina",
    category: "Condo",
    lotSize: "",
    constructionSize: "180",
    pricePerSqm: "$3,027.78",
    price: "545,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Signature Beach Club, Sports activities and Spa, Bicycle trails, 40-room hotel with property management",
    ownerDeveloper: "Michael",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/file/d/1xn9CDHxN8wsMwQULWMfgZHGiyjSRKgZB/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "2028",
    imageUrl: "https://lh3.googleusercontent.com/d/1xn9CDHxN8wsMwQULWMfgZHGiyjSRKgZB=w800",
  },
  {
    name: "Villa 20",
    location: "Blue Venao",
    category: "House",
    lotSize: "300",
    constructionSize: "110",
    pricePerSqm: "$5,318.18",
    price: "585,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Michael/Azuero Rental",
    ownerContact: "507 6225 6363",
    driveFolderLink: "",
    status: "Available",
    legalDocs: true,
    notes: "Can add another bedroom for $40K",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
  },
  {
    name: "Condo F11",
    location: "Blue Venao",
    category: "Apartment",
    lotSize: "",
    constructionSize: "135",
    pricePerSqm: "$2,777.78",
    price: "375,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Michael",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: true,
    notes: "Ground floor apartment",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=500&fit=crop",
  },
  {
    name: "Rio Venao 2BR",
    location: "Playa Venao",
    category: "Duplex",
    lotSize: "300",
    constructionSize: "100",
    pricePerSqm: "$3,200.00",
    price: "320,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "2",
    amenities: "Pool, Terraces",
    ownerDeveloper: "Nadav",
    ownerContact: "507 6444 7221",
    driveFolderLink: "https://drive.google.com/file/d/1UlWBj3pZLav6u8_Lvwllqo7JwR8V1p7r/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Next to new Habat, pre-sale opportunity",
    imageUrl: "https://lh3.googleusercontent.com/d/1UlWBj3pZLav6u8_Lvwllqo7JwR8V1p7r=w800",
  },
  {
    name: "Rio Venao 3BR",
    location: "Playa Venao",
    category: "Duplex",
    lotSize: "300",
    constructionSize: "117",
    pricePerSqm: "$3,247.86",
    price: "380,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "2",
    amenities: "Pool, Terraces",
    ownerDeveloper: "Nadav",
    ownerContact: "507 6444 7221",
    driveFolderLink: "https://drive.google.com/file/d/1UlWBj3pZLav6u8_Lvwllqo7JwR8V1p7r/view?usp=sharing",
    status: "Available",
    legalDocs: true,
    notes: "Next to new Habat, pre-sale opportunity",
    imageUrl: "https://lh3.googleusercontent.com/d/1UlWBj3pZLav6u8_Lvwllqo7JwR8V1p7r=w800",
  },
  {
    name: "Condo B11",
    location: "Blue Venao",
    category: "Condo",
    lotSize: "",
    constructionSize: "126",
    pricePerSqm: "$2,896.83",
    price: "365,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Melanie/Michael",
    ownerContact: "1 303 667 9340",
    driveFolderLink: "",
    status: "Available",
    legalDocs: true,
    notes: "Ground floor apartment, currently rented ($2,300/mo)",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop",
  },
  {
    name: "Vervana",
    location: "La Playita",
    category: "Condo",
    lotSize: "",
    constructionSize: "101",
    pricePerSqm: "",
    price: "",
    bedrooms: "2",
    bathrooms: "2",
    parking: "",
    amenities: "Secluded beach, Private pool, Security 24/7, Sundeck, Restaurant, Fitness center, Lobby, Owners lounge",
    ownerDeveloper: "Carlos Orillac",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/drive/folders/1IzrWneGK31jggo7NcIY0_SxXNYvnpvXR?usp=share_link",
    status: "Available",
    legalDocs: true,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
  },
  {
    name: "Cocobolo PH",
    location: "Playa Venao",
    category: "Condo",
    lotSize: "",
    constructionSize: "355.94",
    pricePerSqm: "",
    price: "1,100,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "2",
    amenities: "",
    ownerDeveloper: "Caroline",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/drive/folders/1eKAaCJwBio2qVZjxJhugZNXiUTed121q?usp=share_link",
    status: "Available",
    legalDocs: true,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
  },
  {
    name: "Cocobolo 2BR",
    location: "Playa Venao",
    category: "Condo",
    lotSize: "",
    constructionSize: "166.8",
    pricePerSqm: "",
    price: "580,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "",
    ownerDeveloper: "Caroline",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/drive/folders/1eKAaCJwBio2qVZjxJhugZNXiUTed121q?usp=share_link",
    status: "Available",
    legalDocs: true,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
  },
  {
    name: "Cocobolo Studio",
    location: "Playa Venao",
    category: "Condo",
    lotSize: "",
    constructionSize: "123.09",
    pricePerSqm: "",
    price: "440,000",
    bedrooms: "1",
    bathrooms: "1",
    parking: "1",
    amenities: "",
    ownerDeveloper: "Caroline",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/drive/folders/1eKAaCJwBio2qVZjxJhugZNXiUTed121q?usp=share_link",
    status: "Available",
    legalDocs: true,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
  },
  {
    name: "Raya del Sol",
    location: "Playa Raya",
    category: "Lot + Villa",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "3",
    bathrooms: "3",
    parking: "2",
    amenities: "Beachfront, Beach access, Food garden, 12 acres",
    ownerDeveloper: "Matt",
    ownerContact: "",
    driveFolderLink: "https://drive.google.com/drive/folders/1kSCERH7pK3P40TSdEGi8ueebI9HWIdB9?usp=share_link",
    status: "Available",
    legalDocs: true,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=500&fit=crop",
  },
];

export function searchProperties(query: string): Property[] {
  const q = query.toLowerCase();
  return PROPERTIES.filter((p) => {
    const searchable = [
      p.name,
      p.location,
      p.category,
      p.amenities,
      p.price,
      p.notes,
      p.bedrooms ? `${p.bedrooms} bedroom` : "",
      p.bathrooms ? `${p.bathrooms} bathroom` : "",
    ]
      .join(" ")
      .toLowerCase();
    return q.split(" ").some((word) => word.length > 2 && searchable.includes(word));
  });
}
