import { Property } from "./types";

// Hardcoded from CIRCA-PROPERTY LISTING Google Sheet
// Spreadsheet ID: 17nryG-WPTeSxC1n2XiPuRZ1h2CByXUQPlttul35P6Ck
// Images are placeholder illustrations until Drive integration is ready
export const PROPERTIES: Property[] = [
  {
    name: "Casa Valley",
    location: "Playa Venao",
    category: "Project",
    lotSize: "600",
    constructionSize: "280",
    pricePerSqm: "",
    price: "550,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Commercial area, Green areas, Padel courts",
    ownerDeveloper: "Papaya Holdings (Tomer)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 3 months",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=500&fit=crop",
  },
  {
    name: "Villa Brisa",
    location: "Venao Village",
    category: "House",
    lotSize: "646",
    constructionSize: "272",
    pricePerSqm: "",
    price: "900,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "2",
    amenities: "Pool, BBQ, Solar, Guests house",
    ownerDeveloper: "Green Ace (Aviad)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 6 months",
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=500&fit=crop",
  },
  {
    name: "Duplex Villa",
    location: "Lomas Venao",
    category: "Duplex",
    lotSize: "488",
    constructionSize: "180",
    pricePerSqm: "",
    price: "500,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Pool, Outdoor areas",
    ownerDeveloper: "VEO Construction (Oded)",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Ready in 3 months",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=500&fit=crop",
  },
  {
    name: "Villa Marina 402",
    location: "Villa Marina",
    category: "House",
    lotSize: "",
    constructionSize: "180",
    pricePerSqm: "",
    price: "650,000",
    bedrooms: "3",
    bathrooms: "2",
    parking: "1",
    amenities: "Pool, Future plans, BBQ area",
    ownerDeveloper: "Azul",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Completely furnished",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=500&fit=crop",
  },
  {
    name: "Casa Ceviche",
    location: "Blue Venao",
    category: "House",
    lotSize: "300",
    constructionSize: "160",
    pricePerSqm: "",
    price: "725,000",
    bedrooms: "3",
    bathrooms: "3",
    parking: "1",
    amenities: "Beach Club, BBQ area",
    ownerDeveloper: "Pirawa Properties",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Completely furnished",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=500&fit=crop",
  },
  {
    name: "Blue B21",
    location: "Blue Venao",
    category: "Apartment",
    lotSize: "",
    constructionSize: "107",
    pricePerSqm: "",
    price: "350,000",
    bedrooms: "2",
    bathrooms: "2",
    parking: "1",
    amenities: "Beach Club, Terrace area",
    ownerDeveloper: "Michael / Azuero Rental",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Furnished",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=500&fit=crop",
  },
  {
    name: "Villa Umutu",
    location: "Canas",
    category: "House",
    lotSize: "3342",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Pool, Terrace, Solar, Ocean view",
    ownerDeveloper: "Margarita",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Furnished",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
  },
  {
    name: "Surf Lodge Residence",
    location: "Playa Venao",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Surf lodge, Beach access",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "Pre-sale investors",
    imageUrl: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=500&fit=crop",
  },
  {
    name: "Blue Venao Duplex 47B",
    location: "Blue Venao",
    category: "Duplex",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Beach Club",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=500&fit=crop",
  },
  {
    name: "Hermitage El Ciruelo",
    location: "El Ciruelo",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Mountain views, Nature",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=500&fit=crop",
  },
  {
    name: "Shahak Mountain",
    location: "Mountain area",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Mountain views",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&h=500&fit=crop",
  },
  {
    name: "Solaris Moledet",
    location: "Moledet",
    category: "Project",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Solar powered",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=500&fit=crop",
  },
  {
    name: "Villa Oro",
    location: "Playa Venao",
    category: "House",
    lotSize: "",
    constructionSize: "",
    pricePerSqm: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    parking: "",
    amenities: "Pool, Ocean view",
    ownerDeveloper: "",
    ownerContact: "",
    driveFolderLink: "",
    status: "Available",
    legalDocs: false,
    notes: "",
    imageUrl: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&h=500&fit=crop",
  },
];

export function searchProperties(query: string): Property[] {
  const q = query.toLowerCase();
  return PROPERTIES.filter((p) => {
    const searchable = [
      p.name,
      p.location,
      p.category,
      p.amenities,
      p.price,
      p.notes,
      p.bedrooms ? `${p.bedrooms} bedroom` : "",
      p.bathrooms ? `${p.bathrooms} bathroom` : "",
    ]
      .join(" ")
      .toLowerCase();
    return q.split(" ").some((word) => word.length > 2 && searchable.includes(word));
  });
}
